set ignorecase
" set smartcase
set hidden
set nowrap
set ruler
set grepprg=ack\ -a
set grepformat=%f:%l:%m
set sts=2
set shiftwidth=2
set tabstop=2
" set autoindent
set expandtab
set number
set hlsearch
set incsearch
set history=1000
set wildmode=list:longest
set scrolloff=5
set lines=50
set columns=165
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set cursorline
set backspace=indent,eol,start
set guicursor=a:blinkon0
set guifont=Droid\ Sans\ Mono:h16

syntax on
filetype on
filetype plugin on
" filetype indent on
" highlight CursorLine guibg=#eeeeee
" " au BufWinEnter * let w:m1=matchadd('Search', '\%<81v.\%>77v', -1)
" au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>75v.\+', -1)
" au WinEnter * let w:m2=matchadd('ErrorMsg', '\%>75v.\+', -1)
au BufRead,BufNewFile *.haml* set filetype=haml
au BufRead,BufNewFile *.slim* set filetype=slim

let NERDTreeIgnore=['\~$', '\.pyc$']

" Functions
function! ToggleScratch()
  if expand('%') == g:ScratchBufferName
    quit
  else
    Sscratch
  endif
endfunction

" remap
let mapleader = ","
" map  <silent> <leader>s :call ToggleScratch()<CR>
map  <unique> <silent> <Leader>t <Plug>PeepOpen
map  <silent> <unique> <Leader>cd <Plug>RooterChangeToRootDirectory
map  <silent> <leader>b :FufBuffer<CR>
map  <silent> <C-N> :silent noh<CR>
map  <silent> <leader>n :NERDTreeToggle<CR>
map  <silent> <S-F5> :ruby finder.rescan!<ENTER>
map  <leader>l <C-W>l
map  <leader>j <C-W>j
map  <leader>k <C-W>k
map  <leader>h <C-W>h
map  <F1> <ESC>
imap <F1> <ESC>
nmap <silent> <leader>L :set list!<CR>
vmap gl :<C-U>!git blame <C-R>=expand("%:p") <CR> \| sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>

set pastetoggle=<F2>
" map <leader>t :FuzzyFinderTextMate<CR>

color solarized

let g:fuzzy_ceiling="1000"
let g:fuzzy_ignore="log/**;coverage/**;tmp/**;public/images/**;public/system/**;doc/**;script/**;solr/**;public/secure_photos/**;vendor/**;*.pyc"
let g:fuzzy_matching_limit="10"
let g:fuzzy_enumerating_limit="10"

" Django template surround stuff
let g:surround_{char2nr("b")} = "{% block\1 \r..*\r &\1 %}\r{% endblock %}"
let g:surround_{char2nr("i")} = "{% if\1 \r..*\r &\1 %}\r{% endif %}"
let g:surround_{char2nr("w")} = "{% with\1 \r..*\r &\1 %}\r{% endwith %}"
let g:surround_{char2nr("c")} = "{% comment\1 \r..*\r &\1 %}\r{% endcomment %}"
let g:surround_{char2nr("f")} = "{% for\1 \r..*\r &\1 %}\r{% endfor %}"

" Highlight extra whitespace
highlight ExtraWhitespace ctermbg=red guibg=#fff600
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" function to delete all hidden buffers
function! Wipeout()
  " list of *all* buffer numbers
  let l:buffers = range(1, bufnr('$'))

  " what tab page are we in?
  let l:currentTab = tabpagenr()
  try
    " go through all tab pages
    let l:tab = 0
    while l:tab < tabpagenr('$')
      let l:tab += 1

      " go through all windows
      let l:win = 0
      while l:win < winnr('$')
        let l:win += 1
        " whatever buffer is in this window in this tab, remove it from
        " l:buffers list
        let l:thisbuf = winbufnr(l:win)
        call remove(l:buffers, index(l:buffers, l:thisbuf))
      endwhile
    endwhile

    " if there are any buffers left, delete them
    if len(l:buffers)
      execute 'bwipeout' join(l:buffers)
    endif
  finally
    " go back to our original tab page
    execute 'tabnext' l:currentTab
  endtry
endfunction

" mapping for function above
map <C-W>x :call Wipeout()<CR>

