alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ls='ls -G'
alias l='ls -al'
alias ll='ls -l'
alias la='ls -al'
alias rm='rm -i'
alias o=open
alias vim='mvim'
alias m='mate -w'
alias gs='git status'
alias gst='git status'
alias gco='git co'
alias gci='git ci'
alias gad='git add'
alias gmr='git merge'
alias gdf='git diff'
alias grs='git reset'
alias gps='git push'
alias gpl='git pull'
alias gbr='git branch'
alias gpp='git pull && git push'
alias gre='git rebase'
alias sc='./script/console'
alias ss='./script/server'
alias dj='django-admin.py'
alias sf='cd ~/code/sinefunc'
alias sg='script/generate'
alias cdlt='cd ~/code/sinefunc/lt'
alias cds='cd ~/code/sinefunc'
alias cdbs='cd ~/code/sinefunc/boughtstuff'
alias pp='parkplace'
alias rvm_en='source $HOME/.rvm/scripts/rvm'
alias monggr_env='source $HOME/py_envs/monggr/bin/activate'
alias dj_env='source $HOME/py_envs/django1.1/bin/activate'
alias pg_start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg_stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

alias node-repl="rlwrap node-repl"
alias cl=clear
alias ea='vi ~/bin/dotfiles/shells/bash/bash_aliases && source ~/bin/dotfiles/shells/bash/bash_aliases'

function gc {
  git commit -m "$*"
}
alias stakestories="rstakeout 'monk stories' app/**/*.* test/**/*.rb"
alias staketest="rstakeout 'monk test' app/**/*.* test/**/*.rb"
