alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ls='ls -G'
alias l='ls -al'
alias ll='ls -l'
alias la='ls -al'
alias rm='rm -i'
alias o=open
alias vim='mvim'
alias m='mate -w'
alias gs='git status'
alias gst='git status'
alias gco='git co'
alias gci='git ci'
alias gad='git add'
alias gmr='git merge'
alias gdf='git diff'
alias grs='git reset'
alias gps='git push'
alias gpl='git pull'
alias gbr='git branch'
alias gpp='git pull && git push'
alias gre='git rebase'
alias sc='./script/console'
alias ss='./script/server'
alias dj='django-admin.py'
alias sg='script/generate'
alias pp='parkplace'
alias rvm_en='source $HOME/.rvm/scripts/rvm'
alias monggr_env='source $HOME/py_envs/monggr/bin/activate'
alias dj_env='source $HOME/py_envs/django1.1/bin/activate'
alias pg_start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg_stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

alias node-repl="rlwrap node-repl"
alias cl=clear
alias ea='vi ~/bin/dotfiles/shells/bash/bash_aliases && source ~/bin/dotfiles/shells/bash/bash_aliases'

function gc {
  git commit -m "$*"
}
alias stakestories="rstakeout 'monk stories' app/**/*.* test/**/*.rb"
alias staketest="rstakeout 'monk test' app/**/*.* test/**/*.rb"

# http://discussions.apple.com/message.jspa?messageID=10310875
alias slsmooth="defaults -currentHost write -globalDomain AppleFontSmoothing -int 2"

alias git=hub
alias t='ruby -Ilib:test'
alias ev='`$EDITOR` ~/.gvimrc'
alias "brew.mongo"='mongod run --config /usr/local/Cellar/mongodb/1.6.5-x86_64/mongod.conf'
alias "brew.mysql.server"='mysql.server start'
alias rc="rails c"
alias rs="rails s"
alias rg="rails g"

function goog {
  open `ruby -rcgi -e "puts \"http://google.com/search?q=#{CGI.escape(ARGV.join(' '))}\"" $*`
}

function rbdoc {
  open http://ruby-doc.org/core/classes/"$*".html
}
